#@package _global_
defaults:
  - /mephisto/blueprint: parlai_chat
  - /mephisto/architect: local
  - /mephisto/provider: mock
mephisto:
  blueprint:
    world_file: ${task_dir}/utils/worlds.py
    # custom_source_bundle: ${task_dir}/webapp
    task_description_file: ${task_dir}/task_description.html
    context_jsonl: ${task_dir}/dialogues.jsonl
  task:
    # We expect to be able to handle 25 concurrent conversations without issue
    max_num_concurrent_units: 50 # 25 convos * 2 people per
    task_name: parlai-chat-pizzaria
    task_title: "Pizzzabot"
    task_description: >
      This is a simple chat between two people
      used to demonstrate the functionalities around using Mephisto
      for ParlAI tasks.
    task_reward: 0.3
    task_tags: "dynamic,chat,testing"